name: merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    types:
      - labeled
  pull_request:
    types:
      - labeled
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: bumpr - Bump version when merging Pull Request with specific labels
        uses: haya14busa/action-bumpr@v1
